const TEMPLATE = "#card-template",
  CARD = ".card",
  CARD_IMAGE = ".card__image",
  CARD_TITLE = ".card__title",
  DELETE_BTN = ".card__delete-button",
  LIST = ".places__list",
  POPUP = ".popup",
  POPUP_IS_OPENED = "popup_is-opened",
  POPUP_ClOSE = ".popup__close",
  PROFILE_EDIT_BTN = ".profile__edit-button",
  POPUP_TYPE_EDIT = ".popup_type_edit",
  PROFILE_ADD_BTN = ".profile__add-button",
  POPUP_TYPE_NEW_CARD = ".popup_type_new-card",
  POPUP_TYPE_IMAGE = ".popup_type_image",
  POPUP_IMAGE = ".popup__image",
  POPUP_CAPTION = ".popup__caption",
  PROFILE_TITLE = ".profile__title",
  PROFILE_DESCRIPTION = ".profile__description",
  EDIT_PROFILE_FORM_NAME = "edit-profile",
  NEW_CARD_FORM_NAME = ".popup_type_new-card",
  FORM_EDIT_PROFILE_NAME = ".popup__input_type_name",
  FORM_EDIT_PROFILE_NAME_INPUT = "name",
  FORM_EDIT_PROFILE_DESCRIPTION = ".popup__input_type_description",
  FORM_EDIT_PROFILE_NAME_DESCRIPTION = "description",
  INPUT_TYPE_CARD_NAME = ".popup__input_type_card-name",
  INPUT_TYPE_URL = ".popup__input_type_url",
  CARD_LIKE_BTN = ".card__like-button",
  LIKE_BTN_IS_ACTIVE = "card__like-button_is-active",
  POPUP_IS_ANIMATED = 'popup_is-animated',
  POPUP_FORM = ".popup__form";

export {
  TEMPLATE,
  CARD,
  CARD_IMAGE,
  CARD_TITLE,
  DELETE_BTN,
  LIST,
  POPUP,
  POPUP_IS_OPENED,
  POPUP_ClOSE,
  PROFILE_EDIT_BTN,
  POPUP_TYPE_EDIT,
  PROFILE_ADD_BTN,
  POPUP_TYPE_NEW_CARD,
  POPUP_TYPE_IMAGE,
  POPUP_CAPTION,
  POPUP_IMAGE,
  PROFILE_TITLE,
  PROFILE_DESCRIPTION,
  FORM_EDIT_PROFILE_NAME,
  FORM_EDIT_PROFILE_DESCRIPTION,
  POPUP_FORM,
  EDIT_PROFILE_FORM_NAME,
  FORM_EDIT_PROFILE_NAME_INPUT,
  FORM_EDIT_PROFILE_NAME_DESCRIPTION,
  NEW_CARD_FORM_NAME,
  INPUT_TYPE_CARD_NAME,
  INPUT_TYPE_URL,
  CARD_LIKE_BTN,
  LIKE_BTN_IS_ACTIVE,
  POPUP_IS_ANIMATED,
};
